name: Build CVs

on:
  push:
    branches:
      - main

jobs:
  built-pdf-cv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.6.1"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Define a cache dependency glob
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install the project
        run: uv sync --no-dev

      - name: Convert md to pdf
        run: uv run export_cv.py
        env:
          PHONE: ${{ secrets.PHONE }}
          EMAIL: ${{ secrets.EMAIL }}

      - name: Upload CVs
        uses: actions/upload-artifact@v4
        with:
          name: PDF CVs
          path: './build'
